### ISSUE TITLE
Deleting WooCommerce product causes fatal error when ACF plugin is activated

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#542]
Clean install with all latest versions:

Wordpress: Version 6.1.1
Breakdance: Version 1.1-beta.1
WooCommerce: Version 7.1.0
Advanced Custom Fields PRO: Version 6.0.4

**Steps to reproduce:** 

Activate all plugins
Imported WooCommerce Sample products
Delete a WooCommerce product
Go to products bin and click empty bin

**This causes fatal error:**

```
Fatal error: Uncaught TypeError: array_filter(): Argument

#1 ($array) must be of type array, bool given in /wp-content/plugins/breakdance/plugin/acf-breakdance-content/acf-block.cpt.php:41 

Stack trace: 

#0 /wp-content/plugins/breakdance/plugin/acf-breakdance-content/acf-block.cpt.php(41): array_filter() 
#1 /wp-includes/class-wp-hook.php(310): Breakdance\Blocks\deleteAcfContentBlocks() 
#2 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() 
#3 /wp-includes/plugin.php(517): WP_Hook->do_action() 
#4 /wp-includes/post.php(3407): do_action() 
#5 /wp-admin/edit.php(184): wp_delete_post() 
#6 {main} thrown in /wp-content/plugins/breakdance/plugin/acf-breakdance-content/acf-block.cpt.php on line 41
```

**Comment by JeusuDigital** [comment]
This looks like it is now fixed in breakdance-1.1-beta.2
