### ISSUE TITLE
Activating Breakdance plugin Lib mozart scoped psr4

### ISSUE THREAD

**Issue by Hakira-Shymuy** [soflyy/breakdance-bugs#781]
**What version of Breakdance are you using?**
alpha 1.3

**What browser are you using?**
chrome

**What operating system are you using?**
windows

Server
Vultr HF 
1vCPU
64GB NVMe
Ubuntu 20.04 LTS x64
php 8.1

Debug.log

`[12-Apr-2023 22:58:01 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/tmp/breakdance/twig-auto-generated-cache/6d). in removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Cache/FilesystemCache.php:53
Stack trace:
#0 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(352): Breakdance\Lib\Vendor\Twig\Cache\FilesystemCache->write()
#1 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(312): Breakdance\Lib\Vendor\Twig\Environment->loadTemplate()
#2 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(280): Breakdance\Lib\Vendor\Twig\Environment->load()
#3 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/render/twig.php(219): Breakdance\Lib\Vendor\Twig\Environment->render()
#4 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/render/renderer.php(336): Breakdance\Render\Twig->runTwig()
#5 [internal function]: Breakdance\Render\{closure}()
#6 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/render/renderer.php(342): array_reduce()
#7 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/render/cache.php(218): Breakdance\Render\cssForGlobalStyles()
#8 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/setup/clean-cache.php(22): Breakdance\Render\generateCacheForGlobalSettings()
#9 removed-domain.pt/htdocs/wp-includes/class-wp-hook.php(308): Breakdance\Setup\cleanCacheWhenCacheCountChanges()
#10 removed-domain.pt/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#11 removed-domain.pt/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin.php(39): do_action()
#13 removed-domain.pt/htdocs/wp-includes/class-wp-hook.php(308): {closure}()
#14 removed-domain.pt/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 removed-domain.pt/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 removed-domain.pt/htdocs/wp-settings.php(486): do_action()
#17 removed-domain.pt/wp-config.php(137): require_once('...')
#18 removed-domain.pt/htdocs/wp-load.php(55): require_once('...')
#19 removed-domain.pt/htdocs/wp-blog-header.php(13): require_once('...')
#20 removed-domain.pt/htdocs/index.php(17): require('...')
#21 {main}
  thrown in removed-domain.pt/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Cache/FilesystemCache.php on line 53
[12-Apr-2023 22:58:01 UTC] PHP Notice:  Function is_embed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in removed-domain.pt/htdocs/wp-includes/functions.php on line 5865
[12-Apr-2023 22:58:01 UTC] PHP Notice:  Function is_search was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in removed-domain.pt/htdocs/wp-includes/functions.php on line 5865`

I have another site in the same server, same system, same settings, same versions, and everything is completely Okay
this one, doesnt matter what i do, gives me that error

However, tried to install V1.2 , works perfectly
changing to Alpha 1.3 gives me white screen of death
I can send you guys login, but will not do any good bcs as soon as it gets activated i need to remove the plugin completely by deleting the folder or deactivating on the DB

Just to let you guys know

**Comment by a-dubiel** [comment]
Hey, thanks for this report. We are aware of this bug. Will be fixed in the next release.

**Comment by Hakira-Shymuy** [comment]
@a-dubiel any temporary workaround?
